export interface MealDataObject {
  idMeal: string; // "52925",
  strMeal: string; // "Split Pea Soup",
  strDrinkAlternate: string|null; // null,
  strCategory: string; // "Side",
  strArea: string|null; // "Canadian",
  strInstructions: string|null; // "Put the gammon in a very large pan with 2 litres water and bring to the boil. Remove from the heat and drain off the water – this helps to get rid of some of the saltiness. Recover with 2 litres cold water and bring to the boil again. Put everything but the frozen peas into the pan and bring to the boil. Reduce to a simmer and cook for 1½-2½ hrs, topping up the water as and when you need to, to a similar level it started at. As the ham cooks and softens, you can halve it if you want, so it is all submerged under the liquid. When the ham is tender enough to pull into shreds, it is ready.\r\nLift out the ham, peel off and discard the skin. While it is still hot (wear a clean pair of rubber gloves), shred the meat. Remove bay from the soup and stir in the frozen peas. Simmer for 1 min, then blend until smooth. Add a splash of water if too thick, and return to the pan to heat through if it has cooled, or if you are making ahead.\r\nWhen you are ready to serve, mix the hot soup with most of the ham – gently reheat if made ahead. Serve in bowls with the remaining ham scattered on top, and eat with crusty bread and butter.",
  strMealThumb: string|null; // "https://www.themealdb.com/images/media/meals/xxtsvx1511814083.jpg",
  strTags: string|null; // "Soup,Warm",
  strYoutube: string|null; // "https://www.youtube.com/watch?v=qdhWz7qAaCU",
  strIngredient1: string|null; // "Ham",
  strIngredient2: string|null; // "Peas",
  strIngredient3: string|null; // "Onions",
  strIngredient4: string|null; // "Carrots",
  strIngredient5: string|null; // "Bay Leaves",
  strIngredient6: string|null; // "Celery",
  strIngredient7: string|null; // "Frozen Peas",
  strIngredient8: string|null; // "Bread",
  strIngredient9: string|null; // "",
  strIngredient10: string|null; // "",
  strIngredient11: string|null; // "",
  strIngredient12: string|null; // "",
  strIngredient13: string|null; // "",
  strIngredient14: string|null; // "",
  strIngredient15: string|null; // "",
  strIngredient16: string|null; // "",
  strIngredient17: string|null; // "",
  strIngredient18: string|null; // "",
  strIngredient19: string|null; // "",
  strIngredient20: string|null; // "",
  strMeasure1: string|null; // "1kg",
  strMeasure2: string|null; // "200g (soaked overnight)",
  strMeasure3: string|null; // "2 chopped",
  strMeasure4: string|null; // "2 chopped",
  strMeasure5: string|null; // "2",
  strMeasure6: string|null; // "1 chopped",
  strMeasure7: string|null; // "300g",
  strMeasure8: string|null; // "to serve",
  strMeasure9: string|null; // "",
  strMeasure10: string|null; // "",
  strMeasure11: string|null; // "",
  strMeasure12: string|null; // "",
  strMeasure13: string|null; // "",
  strMeasure14: string|null; // "",
  strMeasure15: string|null; // "",
  strMeasure16: string|null; // "",
  strMeasure17: string|null; // "",
  strMeasure18: string|null; // "",
  strMeasure19: string|null; // "",
  strMeasure20: string|null; // "",
  strSource: string|null; // "https://www.bbcgoodfood.com/recipes/1022639/split-pea-and-green-pea-smoked-ham-soup",
  strImageSource: string|null; // null,
  strCreativeCommonsConfirmed: string|null; // null,
  dateModified: string|null; // null
}
